### ISSUE TITLE
API routes for the backend 

### ISSUE THREAD

**Issue by Itsfoss0** [CynthiaWahome/ewaste-recycling-solutions#2]
```
/api/auth/register - POST
/api/auth/login - POST   
/api/trash/ - GET  
/api/trash/ - POST  
/api/trash/{id} - GET
/api/trash/{id} - DELETE
/api/trash/{id} - PATCH / PUT
/api/trash/{id}/changeStatus - PUT
/api/trash/nearby - GET 
```

**Comment by CynthiaWahome** [comment]
> ```
> /api/auth/register - POST
> /api/auth/login - POST   
> /api/trash/ - GET  
> /api/trash/ - POST  
> /api/trash/{id} - GET
> /api/trash/{id} - DELETE
> /api/trash/{id} - PATCH / PUT
> /api/trash/{id}/changeStatus - PUT
> /api/trash/nearby - GET 
> ```

This is done.
Good job @Itsfoss0
