### ISSUE TITLE
Add UI for the project

### ISSUE THREAD

**Issue by Itsfoss0** [CynthiaWahome/ewaste-recycling-solutions#3]
- Handle user auth, creating a login and a signup page, and get them to work with the api (REST)
- Handle Creating of trash orders and other trash operations

**Comment by CynthiaWahome** [comment]
> * Handle user auth, creating a login and a signup page, and get them to work with the api (REST)
> * Handle Creating of trash orders and other trash operations

Done and dusted.
Way to go @Itsfoss0
